services:
  db:
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlyfoods_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000" # เปิดพอร์ต 8000 ให้เรียกใช้งาน API ได้โดยตรง
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=onlyfoods_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80" # หรือพอร์ตที่ Frontend ของคุณรันอยู่ (เช่น 3000 หรือ 5173 ตาม Dockerfile)
    depends_on:
      - backend

volumes:
  db_data: