services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlyfoods_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    restart: always
    # ไม่ต้อง expose port 8080 ออกข้างนอกแล้ว ให้ Proxy จัดการให้
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=onlyfoods_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    # ไม่ต้อง expose port 80 ออกข้างนอกแล้ว ให้ Proxy จัดการให้
    depends_on:
      - backend

  # เพิ่ม Service ใหม่สำหรับรับ Request ทั้งหมดที่พอร์ต 80
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  db_data: