events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. ถ้า Request มีคำว่า /api ให้ส่งข้อมูลไปหา Backend (พอร์ต 8080)
        location /api/ {
            proxy_pass http://backend:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. ถ้าเป็น Request อื่นๆ ให้ส่งไปหา Frontend (พอร์ต 80)
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}